# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'TikTokClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TikTokClone
 
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  target 'TikTokCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TikTokCloneUITests' do
    # Pods for testing
  end

end
